[default]
address = "::"
keep_alive = 5
limits = { file = "20 MiB", data-form = "21 MiB" }
template_dir = "templates"

[debug]
log_level = "debug"
port = 8000

[release]
log_level = "normal"
port = 8000
